#32 位随机字符串：
titaniume: 
  rodmom: ${random.value}
# 随机数 整数：
  number: ${random.int}
#属性占位符：
  name: www.titaniume.com
  desc: ${titaniume.name} is config

#端口配置：
server: 
  port: 8081

#时间格式化:
spring: 
  jackson: 
    date-format: yyyy-MM-dd H